const cds = [
	{
		num: 1,
		artist: 'Stardust',
		relYear: 1998,
		tags: ['house', 'french house', 'dance'],
		album: 'Music Sounds Better With You',
		image: 'cd-img1.webp',
		label: 'Virgin Records',
        rating: 4.1,
		sellers: 70,
		bestPrice: 11.0,
		condition: 'good (G)',
		sellerName: 'Justice4All (FR)',
        shipping: 15.0
	},
	{
		num: 2,
		artist: 'Masayoshi Takanaka',
		relYear: 1981,
		tags: ['jazz fusion', 'rock opera', 'city pop'],
		album: 'The Rainbow Goblins',
		image: 'cd-img2.webp',
		label: 'Kitty Records',
        rating: 3.8,
		sellers: 23,
		bestPrice: 9.0,
		condition: 'near mint (NM)',
		sellerName: 'oswaldJP (JP)',
        shipping: 16.0
	},
	{
		num: 3,
		artist: 'Aphex Twin',
		relYear: 2024,
		tags: ['ambient', 'ambient techno', 'drone'],
		album: 'Selected Ambient Works Volume II (Expanded Edition)',
		image: 'cd-img3.webp',
		label: 'Warp Records',
        rating: 3.9,
		sellers: 9,
		bestPrice: 17.0,
		condition: 'mint (M)',
		sellerName: 'seanboIDM (UK)',
        shipping: 8.0
	},
	{
		num: 4,
		artist: 'crayvxn',
		relYear: 2024,
		tags: ['trance', 'techno', 'hardcore'],
		album: 'Ether Drive',
		image: 'cd-img4.webp',
		label: 'Diverse System',
        rating: 3.5,
		sellers: 8,
		bestPrice: 13.0,
		condition: 'mint (M)',
		sellerName: 'oswaldJP (JP)',
        shipping: 16.0
	},
	{
		num: 5,
		artist: 'Autechre',
		relYear: 2005,
		tags: ['glitch', 'idm', 'electronic'],
		album: 'Untilted',
		image: 'cd-img5.webp',
		label: 'Beat Records',
        rating: 3.7,
		sellers: 40,
		bestPrice: 11.0,
		condition: 'very good (VG)',
		sellerName: 'chronologic (JP)',
        shipping: 16.0
	},
	{
		num: 6,
		artist: 'Harold Budd / Brian Eno',
		relYear: 2004,
		tags: ['ambient', 'piano'],
		album: 'Ambient 2: The Plateaux of Mirror',
		image: 'cd-img6.webp',
		label: 'Virgin Records',
        rating: 3.8,
		sellers: 45,
		bestPrice: 8.0,
		condition: 'good (G)',
		sellerName: 'wreckitRob (UK)',
        shipping: 8.0
	},
	{
		num: 7,
		artist: 'Camellia',
		relYear: 2023,
		tags: ['edm', 'j-core', 'hardcore'],
		album: 'Ashed Wings',
		image: 'cd-img7.webp',
		label: 'EXITTUNES Dance Production',
        rating: 3.4,
		sellers: 5,
		bestPrice: 21.0,
		condition: 'mint (M)',
		sellerName: 'oswaldJP (JP)',
        shipping: 16.0
	},
	{
		num: 8,
		artist: 'Brian Eno',
		relYear: 1990,
		tags: ['ambient', 'modern classical', 'drone'],
		album: 'Discreet Music',
		image: 'cd-img8.webp',
		label: 'Editions EG',
        rating: 3.6,
		sellers: 30,
		bestPrice: 9.0,
		condition: 'good (G)',
		sellerName: 'wreckitRob (UK)',
        shipping: 8.0
	},
	{
		num: 9,
		artist: 'Autechre',
		relYear: 2013,
		tags: ['idm', 'glitch', 'drone'],
		album: 'Exai',
		image: 'cd-img9.webp',
		label: 'Beat Records',
        rating: 3.7,
		sellers: 50,
		bestPrice: 17.0,
		condition: 'near mint (NM)',
		sellerName: 'chronologic (JP)',
        shipping: 16.0
	}
]

export default cds